### ISSUE TITLE
Improve documentation and manual

### ISSUE THREAD

**Issue by scapella** [inab/trimal#15]
The documentation needs to be intensively extended to incorporate the latest improvements.
It is also lacking enough clarity about how to use specific functions.

**Comment by jooolia** [comment]
e.g. example on page 6 ```-select {2,7,20-25,80-100}``` does not work in 1.4. Should be ```-selectcols { 2,7,20-25,80-100 }```. Trimal and bash are quite picky about the spaces.

**Comment by scapella** [comment]
Thanks for noting that down. In coming weeks, I'll release a partially improved documentation to reflect all new changes.

**Comment by nicodr97** [comment]
Solved by #99
