### ISSUE TITLE
Tag a new release? 

### ISSUE THREAD

**Issue by tseemann** [inab/trimal#43]
Lots of commits since 1.4.1   ?

**Comment by scapella** [comment]
@tseemann we are preparing a fully refactored and revamped trimAl version thanks to @Vicfero 

During the process of refactoring and deeply testing the code, we have fixed some bugs and improved parameters compatibilities. 

Do you advice to tag one of this commits as 1.4.2 prior to the major release?

Cheers,

S

**Comment by tseemann** [comment]
No rush - let's just wait until you have 1.5 (or 2.0) ready!

**Comment by nicodr97** [comment]
Solved by #99
